### ISSUE TITLE
CCC-CH Village Finanzbeitrag

### ISSUE THREAD

**Issue by Bouni** [reaktor23/CCCamp2019#19]
Hab ne Mail von vimja bezüglich des Finanzierungsstandes des CCC-CH Villages bekommen:

Aktuelle Auslagen: **3657.65CHF** für Zelt, Tische und Stühle
Aktuelle Einnahmen: **1316.11**

Ich würde sagen das wir uns mit je 100CHF beteiligen sollten, was meint ihr dazu?

**Comment by Sslimon** [comment]
Werde ich auch noch machen 👍

**Comment by Sslimon** [comment]
Ist gemacht

**Comment by ioeides** [comment]
Erledigt
